import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
}

export default function RootLayout(props: Props) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>{props.children}</AuthProvider>
            </body>
        </html>
    );
}
